export declare type SkipMenuConfig = {
    id?: string;
    attachTo?: HTMLElement | null;
    alwaysShow?: boolean;
    buttonId?: string;
    menuId?: string;
    menuContainerId?: string;
    headers?: string | false;
    headings?: string | false;
    tooltipId?: string;
    landmarks?: string | false;
    reloadOnChange?: boolean;
    useAccessKey?: boolean;
    accessKey?: string;
    tabIndex?: number | null;
    isRemoved?: boolean;
    ignoreClass?: string;
    text?: {
        buttonLabel?: string;
        headingsLabel?: string;
        landmarksLabel?: string;
        tooltipLabel?: string;
        controlKeyLabel?: string;
        optionKeyLabel?: string;
        altKeyLabel?: string;
        shiftKeyLabel?: string;
        mainLabel?: string;
        searchLabel?: string;
        navigationLabel?: string;
        regionLabel?: string;
        complementaryLabel?: string;
        bannerLabel?: string;
        footerLabel?: string;
        sectionLabel?: string;
        formLabel?: string;
    };
    ensureAbsoluteParent?: boolean;
    theme?: 'bootstrap' | 'patternfly' | 'full' | undefined;
};
export declare type SkipMenuConfigFull = {
    id: string;
    attachTo: HTMLElement;
    alwaysShow: boolean;
    buttonId: string;
    menuId: string;
    menuContainerId: string;
    mutationObserver: MutationObserver | null;
    headers: string | false;
    headings: string | false;
    tooltipId: string;
    landmarks: string | false;
    reloadOnChange: boolean;
    useAccessKey: boolean;
    accessKey: string;
    tabIndex: number | null;
    isRemoved: boolean;
    ignoreClass: string;
    text: {
        buttonLabel: string;
        headingsLabel: string;
        landmarksLabel: string;
        tooltipLabel: string;
        controlKeyLabel: string;
        optionKeyLabel: string;
        altKeyLabel: string;
        shiftKeyLabel: string;
        mainLabel: string;
        searchLabel: string;
        navigationLabel: string;
        regionLabel: string;
        complementaryLabel: string;
        bannerLabel: string;
        footerLabel: string;
        sectionLabel: string;
        formLabel: string;
    };
    ensureAbsoluteParent?: boolean;
};
export declare const defaultConfig: SkipMenuConfigFull;
